-- =====================================================================
-- john-k9 :: migration 0018 :: create k9_partnership_pair_progress
--
-- WHY THIS FILE EXISTS: KNOWN_ISSUES.md used to disclose "the partnership
-- tenure-bonus anti-farm fix is in-memory only... a resource restart
-- re-opens the exploit once, for any pair that happens to break up and
-- reform around that restart." server/partnership.lua's own header
-- (ANTI-FARM GUARD EXTENSION) and server/tenure.lua's own closing comment
-- block ("TENURE PROGRESSION EXTENSIONS -- FURTHER PROPOSED ADDITIONS",
-- item 3) both proposed the fix in advance: one new table, keyed by the
-- exact (k9_citizenid, handler_citizenid) PAIR rather than by any single
-- `k9_partnerships` row, so the highest partnership-tenure milestone tier
-- that pair has ever confirmed-earned survives that row being superseded
-- by a brand-new one on break+reform -- AND survives a genuine resource
-- restart, which the old in-memory-only table could not. This migration
-- builds exactly that table; server/datastore.lua's new
-- `PairProgress_GetHighestTenureTier`/`PairProgress_UpsertHighestTenureTier`
-- and server/partnership.lua's `CaptureTenureSeedForPair`/establish-time
-- seed read are the code side of this same change.
--
-- WHY A NEW TABLE, NOT A COLUMN ON `k9_partnerships`: a column on the
-- per-instance partnership row cannot survive that row itself being
-- superseded by a brand-new one on reform -- that IS the exact problem
-- this table exists to close. `k9_partnerships.tenure_bonus_tier_granted`
-- (migration 0003) still exists unchanged, and still tracks progress
-- WITHIN one active partnership row; this table separately tracks the
-- ceiling that specific (k9, handler) pair has EVER reached, across every
-- row that pair has ever had.
--
-- WHO NEEDS THIS FILE: any existing installation. `sql/install.sql` is
-- updated in this same pass to create this table directly for a fresh
-- install, per this repo's own "install.sql has final shape, a migration
-- backfills an existing DB" convention (migrations 0001/0005/0007/0008/
-- 0010/0011/0013/0014/0015/0016 all follow the same pattern for a
-- brand-new table) -- see this migration's own rollback file,
-- sql/rollback/0018_down.sql, for the reverse.
--
-- COMPATIBILITY: a brand-new, independent table -- nothing here reads,
-- rewrites, or depends on the shape of any existing row in any other
-- table. Every existing K9/handler pair simply has no row here yet, which
-- resolves exactly like "this exact pair has never earned a milestone
-- tier" (K9Store.PairProgress_GetHighestTenureTier returns nil) -- the
-- same starting point a pair that partnered for the first time today
-- would have.
--
-- IDEMPOTENT / SAFE TO RE-RUN: a bare `CREATE TABLE IF NOT EXISTS` -- no
-- ALTER, no INFORMATION_SCHEMA-guarded stored-procedure dance, matching
-- migrations 0007/0008/0010/0011/0013/0015/0016's own identical reasoning
-- for why a brand-new table needs none of that.
--
-- NO DESTRUCTIVE STATEMENT: this file only ever CREATEs; it never DROPs,
-- TRUNCATEs, ALTERs, or rewrites any existing column, table, or row.
--
-- NO FK, matching this schema's own established "no FK, relational
-- integrity enforced at the application layer" convention -- see
-- sql/install.sql's own header comment on this table for the full
-- reasoning (neither citizenid column references `k9_partnerships`, whose
-- rows are superseded on every reform, which is precisely what this table
-- must outlive).
--
-- ORDERING: independent of every other table in this schema -- neither
-- column is a foreign key into `k9_partnerships` or anywhere else (plain,
-- unvalidated-by-FK strings, matching every other citizenid column in
-- this schema already). Applying this file's numeric filename order after
-- install.sql, as this resource's own migrations directory already
-- documents, always satisfies any real ordering requirement. Not
-- order-dependent on migration 0003 (which added
-- `k9_partnerships.tenure_bonus_tier_granted`) either -- the two columns
-- are read/written independently by server/partnership.lua and
-- server/tenure.lua, never joined in a single query.
--
-- Requires MySQL >= 5.7.8 or MariaDB >= 10.2, matching sql/install.sql --
-- this migration's own table does not individually need that floor (no
-- virtual generated column, just a plain composite PRIMARY KEY), but ships
-- under the same requirement as the rest of this schema for one
-- consistent minimum across the whole resource.
-- =====================================================================

-- ---------------------------------------------------------------------
-- k9_partnership_pair_progress -- see sql/install.sql's own header on this
-- table (added in the same pass) for the full column-by-column writeup;
-- not repeated a second time here.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `k9_partnership_pair_progress` (
  `k9_citizenid`                 VARCHAR(50)       NOT NULL,
  `handler_citizenid`            VARCHAR(50)       NOT NULL,
  `highest_tenure_tier_granted`  TINYINT UNSIGNED  NOT NULL DEFAULT 0,

  PRIMARY KEY (`k9_citizenid`, `handler_citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
